-- Tabela STATS
CREATE TABLE IF NOT EXISTS STATS (
    STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL
    );

-- Widok BESTSELLERS_COUNT
CREATE OR REPLACE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS BESTSELLERS_COUNT
FROM BOOKS
WHERE BESTSELLER = TRUE;

-- Tworzenie zdarzenia
DELIMITER $$
CREATE EVENT IF NOT EXISTS UpdateBestsellersEvent
ON SCHEDULE EVERY 1 DAY STARTS CURRENT_TIMESTAMP
DO
BEGIN
    DECLARE bestsellers_count INT;

SELECT BESTSELLERS_COUNT INTO bestsellers_count FROM BESTSELLERS_COUNT;

INSERT INTO STATS (STAT_DATE, STAT, VALUE)
VALUES (NOW(), 'BESTSELLERS', bestsellers_count);
END $$
DELIMITER ;
